<a href="https://colab.research.google.com/github/Endoefa/ovo/blob/main/Tutorial_One.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## UFMFRR-15-M - Machine Vision Tutorial

# Unit 1 - Python and Google Colab, Grouping

In [1]:
import numpy as np  # import a package (numpy)
import cv2  #  opencv

# !pip list  # list all the packages that have been pre-installed

!python --version  # show python version
print(cv2.__version__)  # show opencv version
print(np.__version__)  #show numpy version

Python 3.13.15
4.14.0
2.1.3


# Test if a GPU is available

In [2]:
!nvidia-smi

Fri Oct  2 08:28:31 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   56C    P8             13W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

# Install a package/library

In [4]:
!pip install keras  # In fact, keras should have been pre-installed in Colab

# Basic data types


In [5]:
x = 5  # int
y = 1.5  # float
z = True  # boolean
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'bool'>


In [6]:
machine = 'machine'
mv = machine + '_' + 'vision'  # concatenation of strings
print(mv)
print(type(mv))

machine_vision
<class 'str'>


* Please refer to some of the [useful string methods](https://docs.python.org/release/3.6.9/library/stdtypes.html#string-methods)

# Lists, Dictionaries, Sets and Tuples

In [7]:
a = [1, 2, 3]
b = ['x', 'y', 'z']
a[1] = 'z'
print(a)
print(b)

[1, 'z', 3]
['x', 'y', 'z']


* More on list [here](https://docs.python.org/release/3.6.9/tutorial/datastructures.html#more-on-lists)
* Read about [Dictionaries](https://docs.python.org/release/3.6.9/library/stdtypes.html#mapping-types-dict), [Sets](https://docs.python.org/release/3.6.9/library/stdtypes.html#set-types-set-frozenset) and [Tuples](https://docs.python.org/release/3.6.9/library/stdtypes.html?highlight=tuple#tuples) yourself

# Numpy

Create a numpy array

In [8]:
a = np.arange(12)
a1 = np.arange(2, 20, 3)  # Return evenly spaced values within a given interval.
b = np.diag(a)  # Extract a diagonal or construct a diagonal array.
print(a)
print(a1)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 2  5  8 11 14 17]
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11]]


Reshape a numpy array

In [9]:
a = a.reshape(3,4)
print(a)
print('The shape of the array is: ' + str(a.shape))
print('The type of the elements: ' + a.dtype.name)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The shape of the array is: (3, 4)
The type of the elements: int64


Add a number to all elements in an array

In [10]:
a = a + 5
print(a)

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Slicing

In [11]:
c = a[0:2,2]
print(c)

[ 7 11]


* More on numpy [here](https://numpy.org/doc/1.18/reference/index.html)